const PDFDocument = require('pdfkit');
const fs = require('fs');

async function testPdfKit() {
  try {
    console.log('Testing PDFKit...');
    
    // Create PDF
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50
    });

    // Collect PDF data
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => {
      console.log('PDF generation completed');
    });

    // Add some content
    doc.fontSize(20).text('Test PDF', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text('This is a test PDF generated by PDFKit.');
    
    doc.end();

    // Wait for PDF generation to complete
    await new Promise(resolve => {
      doc.on('end', resolve);
    });

    const pdfBuffer = Buffer.concat(chunks);
    console.log('PDF buffer length:', pdfBuffer.length);
    
    // Save to file
    fs.writeFileSync('test.pdf', pdfBuffer);
    console.log('PDF saved as test.pdf');
    
  } catch (error) {
    console.error('Error testing PDFKit:', error);
  }
}

testPdfKit();